ALTER TABLE users
  ADD COLUMN account_type VARCHAR(10)  NOT NULL DEFAULT 'HUMAN',
  ADD COLUMN enabled      TINYINT(1)   NOT NULL DEFAULT 1,
  ADD COLUMN first_name   VARCHAR(100) NULL,
  ADD COLUMN last_name    VARCHAR(100) NULL,
  ADD COLUMN phone        VARCHAR(30)  NULL;
